version: '3.1'

services:
  web:
    build: .
    ports:
      -  "8000:8000"
    depends_on:
      -  db
  db:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      -  "5433:5432"
    volumes:
      -  rss-agg-db-data:/var/lib/postgresql/data
volumes:
  rss-agg-db-data:
    driver: local