version: '3.1'

services:
  web:
    build: .
    expose:
      -  8000
    depends_on:
      -  db
  db:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      -  "5433:5432"
    volumes:
      -  rss-agg-db-data:/var/lib/postgresql/data
  nginx:
    build: ./deploy/nginx
    ports:
      -  80:80
      -  443:443
    depends_on:
      -  web
volumes:
  rss-agg-db-data:
    driver: local