"""add_user_to_folder

Revision ID: 05b7d3ef1290
Revises: 82a18715e93c
Create Date: 2023-05-14 16:27:51.516082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b7d3ef1290'
down_revision = '82a18715e93c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_folder', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'source_folder', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_folder', type_='foreignkey')
    op.drop_column('source_folder', 'user_id')
    # ### end Alembic commands ###
