"""Make source name unique

Revision ID: 1a90c686dfb3
Revises: ae1532778373
Create Date: 2023-05-22 16:46:28.431729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a90c686dfb3'
down_revision = 'ae1532778373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'source', ['name'])
    op.create_unique_constraint(None, 'source', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='unique')
    op.drop_constraint(None, 'source', type_='unique')
    # ### end Alembic commands ###
