"""Change folders and sources association

Revision ID: ab6b7d7f44f1
Revises: 1a90c686dfb3
Create Date: 2023-05-23 09:31:01.255707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6b7d7f44f1'
down_revision = '1a90c686dfb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folder_has_source', 'folder_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('folder_has_source', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folder_has_source', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('folder_has_source', 'folder_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
