"""Add icon column

Revision ID: f3322a08da5e
Revises: 95be656cf060
Create Date: 2023-09-11 17:49:05.802881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3322a08da5e'
down_revision = '95be656cf060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('icon', sa.String(length=256), server_default='media/default-icon.jpg', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'icon')
    # ### end Alembic commands ###
